### ISSUE TITLE
List other users

### ISSUE THREAD

**Issue by Jibec** [mbugeia/kanboard_ynh#11]
In my user list, I see my own user but I can't see the other users of my instance. Is this made on purpose ?

**Comment by mbugeia** [comment]
Well my package of Kanboard use the reverse proxy authentification, it means it use the user that the web server (nginx) sent him throught SSOwat. Kanboard has no way to know all the user there are on the system, so it can't display them.
But once an user has logged in into Kanboard, Kanboard knows him and it will be display.

So not exactly a bug but not very convenient either ;)

**Comment by Jibec** [comment]
Ok, so I understand that : 
Kanboard use SSOwat for user authentification (it means it use the user that the web server (nginx) sent him throught SSOwat), but can't list all user of the system.
If you wish to add a user, just log in with that user into Kanboard so the software knows him and displays it.

I'll try my first pull request to change readme so other user will now about :)
