### ISSUE TITLE
The project name is required

### ISSUE THREAD

**Issue by sbDevGit** [mbugeia/kanboard_ynh#14]
I can't create a new project, I give a name, but it didn't get it, and the JavaScript reminder say
"The project name is required"

**Comment by Jean31** [comment]
I have the same issue.
After first installation I manged to create 2 private project some tasks and sub tasks
The next day impossible to create another private project.
"The project name is required"
I didn't found any log ...

I am using yunohost 2.2 on raspberry wheezy up2date.

**Comment by mbugeia** [comment]
Yes it seems the last update broke it :/ I did some test but I still don't understand why. I'm considering downgrading kanboard to v1.0.18 but I have to test if it's possible first.

**Comment by mbugeia** [comment]
This was broken because of a change I made in the config file, it should be fixed now.

Upgrade with sudo yunohost app upgrade -u https://github.com/mbugeia/kanboard_ynh kanboard
