### ISSUE TITLE
Gogs plugin integration : "actionManager" not defined

### ISSUE THREAD

**Issue by Krands** [mbugeia/kanboard_ynh#21]
Hi,

I am trying to add some extensions, but the most important is Gogs one.
I read the documentation written in on the repo's `README.me`, apply it by pasting (aka `scp`) in the right folder (`/var/www/kanboard/plugins`) but it does not work. Here's the error: 
`Internal error : actionManager is not defined`

That's all.

I did not see the error in the original repos, so I am asking you, because wherever I am looking, `actionManager` is mentioned nowhere but in the original code. 

Beside that, I try to add the 'Reverse-Proxy Authentication with LDAP user provider' plugin, some Manager is not defined either.

I must be missing something. :/

Cheers !

**Comment by mbugeia** [comment]
Hi,

I didn't test it but the kanboard version of the package is probably too old for the plugin.
I plan to add the 'Reverse-Proxy Authentication with LDAP user provider' plugin by default in the package.

Also note that the actual package update will remove your plugin during an update, I need to change that.

**Comment by Krands** [comment]
Hi,

Ha ! This explain everything. 😛
If you integrate the reverse proxy authentication, is there a way to integrate Gogs too or we should do it by ourselves ?

**Comment by mbugeia** [comment]
I don't think I will integrate others plugins in the package. The authentification plugin is kind of "core feature" for me but the others are optionnal.
But the package must not remove user installed plugin during an update, that need to be improve.

**Comment by Krands** [comment]
Ho. Heard you.

Thus, we will be able to use the *.ICS files in public mode without having to get into the code?

**Comment by mbugeia** [comment]
Hum, sorry but I don't know what are you talking about.

**Comment by mbugeia** [comment]
I've updated kanboard with the 'Reverse-Proxy Authentication with LDAP user provider' plugin

**Comment by Krands** [comment]
About the *.ICS file, I guess "iCal" is more explicit :-D  
Thank for the upgrade !

**Comment by mbugeia** [comment]
I know what's an ics file is I just didn't know there was one in kanboard.
Now I found it, it's when we put public mode on a project. I didn't know there was an issue with it, I can download it. That's totally unrelated to this issue.
It seems that some url have to be SSO unprotected to properly activate the public mode. I will look into this.

**Comment by Krands** [comment]
Ho okay, I am sorry.

Should I open another issue for this ?

**Comment by mbugeia** [comment]
Yes please. BTW the issue of this thread is resolved IMO, gogs plugin works and I fixed the update thing with plugin.

**Comment by Krands** [comment]
I actually had no time before to upgrade Kanboard. I was answering via my phone.
I am doing it now.

**Comment by Krands** [comment]
Did, and I succeeded to apply Gogs integration. Thanks !

**Comment by mbugeia** [comment]
Opened #27 about public mode
