### ISSUE TITLE
"You must specify an URL to update your locale app Kanboard"

### ISSUE THREAD

**Issue by Eynix** [mbugeia/kanboard_ynh#3]
Hi,

After a 'yunohost app upgrade', I have a warning : 
"ATTENTION: Vous devez spécifier une URL pour mettre à jour votre application locale kanboard"
("WARNING: you must specify an URL in order to update your locale application kanboard", sorry for my eng)

This is all.
Thanks for your great work.

**Comment by mbugeia** [comment]
Hi,
This is normal behavior since kanboard is not an official yunohost app for now. To upgrade you should use this command line:
sudo yunohost app upgrade -u https://github.com/mbugeia/kanboard_ynh kanboard
