### ISSUE TITLE
Blank page on the fresh install

### ISSUE THREAD

**Issue by anmol26s** [mbugeia/kanboard_ynh#7]
Hi
I tried to install Kanboard package on fresh Debian Jessie.
After the installation it shows blank page.

Here is the installation log.
https://datamol.in/zerobin/?0e8433a3ee120099#Mo8Qlqiy8T5bqw+g5ypHbrLEmPsl/wa7HOEMZQazSHE=

Thanks

**Comment by mbugeia** [comment]
Hi, you are right, my last commit was broken some source file were missing. It's fixed now.

Thanks for the report.

**Comment by anmol26s** [comment]
Hi
Thanks for the fixing it. It works with the LDAP but without it do not show login page as it use to show before.

As suggested in this:
https://forum.yunohost.org/t/kanboard-package/78/16
I  modifying the file /var/www/kanboard/config.php and set REVERSE_PROXY_AUTH to false.

Then ran the following command.
sudo yunohost app setting kanboard skipped_uris -v "/"
sudo yunohost app ssowatconf

Now, I have blank page again.

**Comment by mbugeia** [comment]
Since the last version there is a new parameter in config.php

    // Hide login form, useful if all your users use Google/Github/ReverseProxy authentication
    define('HIDE_LOGIN_FORM', true);

You probably want to turn this to false too.

**Comment by anmol26s** [comment]
Thanks it worked

**Comment by anmol26s** [comment]
After last Update I can not login in Kanboard.Entering the user-name and password displays the login screen again. So the login page is in loop ever time entering the user-name and password.

I use Kanboard without Ldap login i.e. without the reverse proxy authentication.

**Comment by mbugeia** [comment]
Ok I assume that you have remodified your config file properly, so that's probably because in the last update I include the plugin "Reverse-Proxy Authentication with LDAP user provider " you need to delete it from /var/www/kanboard/plugins
I need to create a public option for the package for people that use kanboard like you.

**Comment by anmol26s** [comment]
Thanks, removing the plug-in resolved it.
